version: '3.8'

services:
  mottu-csharp-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - ef-tools

  ef-tools:
    build:
      context: .
      dockerfile: Dockerfile
      target: ef-tools-env
    volumes:
      - .:/app
    env_file:
      - .env
